### ISSUE TITLE
Resource schemas

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackage-from-remote-js#3]
As discussed, infer resource schema:
- [x] if the remote does not have resource.schema
- [x] if the remote has resource.schema but this property is not a valid JSON table schema
- [x] if the resource is csv

**Comment by gvidon** [comment]
@pwalsh could you please remind if we should infer schema not just for csv? xls?

**Comment by pwalsh** [comment]
just infer if csv, and add some comment to make that obvious - we'll consider it later.
